server:
  port: 8080

spring:
  sql.init:
    #    mode: always
    mode: never
    platform: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/sk_example_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    open-in-view: false
    generate-ddl: true
